version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: blast_email_redis
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres:15-alpine
    container_name: blast_email_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-blast_email}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: blast_email_backend
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-blast_email}
      - REDIS_URL=redis://redis:6379/0
      - FRONTEND_URL=${FRONTEND_URL}
      - SENDER_NAME=${SENDER_NAME}
      - SENDER_EMAIL=${SENDER_EMAIL}
    depends_on:
      - db
      - redis
    restart: always
    volumes:
      - ./backend/temp_certs:/app/temp_certs
      - ./backend/credentials.json:/app/credentials.json:ro
      - ./backend/token.json:/app/token.json:ro

  celery_worker:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: blast_email_celery
    command: celery -A worker worker -l info
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-blast_email}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
      - backend
    restart: always
    volumes:
      - ./backend/temp_certs:/app/temp_certs
      - ./backend/credentials.json:/app/credentials.json:ro
      - ./backend/token.json:/app/token.json:ro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_EMAIL_ASSET_BASE_URL=${VITE_EMAIL_ASSET_BASE_URL}
        - VITE_LINK_INSTAGRAM=${VITE_LINK_INSTAGRAM}
        - VITE_LINK_LINKEDIN=${VITE_LINK_LINKEDIN}
        - VITE_LINK_GITHUB=${VITE_LINK_GITHUB}
        - VITE_LINK_WEBSITE=${VITE_LINK_WEBSITE}
    container_name: blast_email_frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

volumes:
  postgres_data:
